services:
  - type: web
    name: discord-leaderboard-bot
    env: python
    pythonVersion: "3.10.13"
    region: frankfurt
    plan: free
    healthCheckPath: /health
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
